apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-couchdb
spec:
    storageClassName: standard
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/tmp/couchdb"
