kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: test-couchdb
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: "standard"
