version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - run:
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run:
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          command: |
            sudo minikube start --vm-driver=none
      - run:
          command: |
            sudo minikube update-context
      - run:
          command: |
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          command: |
            sudo kubectl cluster-info
            sudo chown -R $USER ~/.kube ~/.minikube
      - run:
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get -d github.com/gavinzhou/kubec
      - run:
          command: |
            cd ~/.go_workspace/src/github.com/gavinzhou/kubec
            dep ensure
            go run main.go
      - run:
          command: |
            kubectl get pvc,secret